---
title: "RelativeScaling"
author: "David Barkemeyer"
date: "2023-03-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(GTrendsStocks)
library(dplyr)
library(lubridate)
library(progress)

tickers <- sp_500() %>% filter(first_year < 2023) %>% pull(ticker)

int <- interval("2004-01-01", "2023-01-01")
end_date <- lubridate::int_end(int)
ints <- int_split(int, chunk_duration = lubridate::days(120))
overlap <- lubridate::days(60)

pb <- progress_bar$new(total = length(ints))

trends <- purrr::map2_dfr(ints, seq_along(ints), function(int, i) {
  pb$tick()
  
  trends <- gtrendsR::gtrends(
    keyword = tickers,
    geo = "US",
    time = paste(
      lubridate::ymd(lubridate::int_start(int)),
      min(
        as.Date(lubridate::ymd(lubridate::int_end(int)) + overlap),
        as.Date(end_date)
      )
    ),
    onlyInterest = TRUE
  ) %>%
    `[[`("interest_over_time")
  
  print(trends)

  if (is.null(trends)) {
    trends <- tibble::tibble(
      date = lubridate::Date(),
      score = numeric(),
      ticker = character(),
      chunk = i
    )
  } else {
    trends <- trends %>% dplyr::mutate(
      hits = as.numeric(hits),
      keyword = keyword,
      chunk = i
    ) %>%
      dplyr::as_tibble() %>%
      dplyr::select(
        date, score = hits, keyword, chunk
      )
  }

  Sys.sleep(1)
  trends
})
```

